name: Deploy to Cloud Run

on:
  push:
    branches:
      - api-v1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        region: ${{ secrets.GCP_REGION }}
        service: mira-backend
        image: gcr.io/${{ secrets.GCP_PROJECT }}/mira-backend
