name: Deploy to Cloud Run

on:
  push:
    branches:
      - api-v1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/mira-backend

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy mira-backend \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/mira-backend \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated
