name: Deploy to Cloud Run

on:
  push:
    branches:
      - api-v1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@main
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}
        image: gcr.io/${{ secrets.GCP_PROJECT }}/mira-backend
        region: ${{ secrets.GCP_REGION }}
